# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

CONSIDER_BELOW=4000000

PREV_FIB=1
CURRENT_FIB=2
SUM=0

while [ $CURRENT_FIB -le $CONSIDER_BELOW ]
do
    if [ $((CURRENT_FIB % 2)) -eq 0 ]
    then
        SUM=$((SUM + CURRENT_FIB))
    fi
    TMP=$CURRENT_FIB
    CURRENT_FIB=$((CURRENT_FIB + PREV_FIB))
    PREV_FIB=$TMP
done

echo $SUM